# build astro
FROM oven/bun:latest AS builder
WORKDIR /app

ARG PUBLIC_SITE_URL
ENV PUBLIC_SITE_URL=${PUBLIC_SITE_URL}

COPY package.json bun.lock* ./
RUN bun install
COPY . .
RUN bun run build

# serve by nginx
FROM nginx:latest
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
